//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaxCheckNS.Mobile.AppResources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VaxCheckNS.Mobile.AppResources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string NewScanButtonText {
            get {
                return ResourceManager.GetString("NewScanButtonText", resourceCulture);
            }
        }
        
        internal static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        internal static string ScanErrorMessage {
            get {
                return ResourceManager.GetString("ScanErrorMessage", resourceCulture);
            }
        }
        
        internal static string ScanErrorTitleText {
            get {
                return ResourceManager.GetString("ScanErrorTitleText", resourceCulture);
            }
        }
        
        internal static string ScanSuccessDetailText {
            get {
                return ResourceManager.GetString("ScanSuccessDetailText", resourceCulture);
            }
        }
        
        internal static string ScanSuccessTitleText {
            get {
                return ResourceManager.GetString("ScanSuccessTitleText", resourceCulture);
            }
        }
        
        internal static string ViewGuideButtonText {
            get {
                return ResourceManager.GetString("ViewGuideButtonText", resourceCulture);
            }
        }
        
        internal static string VaccineCodeInvalidText {
            get {
                return ResourceManager.GetString("VaccineCodeInvalidText", resourceCulture);
            }
        }
        
        internal static string VaccineDateInvalidText {
            get {
                return ResourceManager.GetString("VaccineDateInvalidText", resourceCulture);
            }
        }
        
        internal static string VaccineDosageInvalidText {
            get {
                return ResourceManager.GetString("VaccineDosageInvalidText", resourceCulture);
            }
        }
        
        internal static string FhirFormatInvalidText {
            get {
                return ResourceManager.GetString("FhirFormatInvalidText", resourceCulture);
            }
        }
        
        internal static string InvalidScanText {
            get {
                return ResourceManager.GetString("InvalidScanText", resourceCulture);
            }
        }
        
        internal static string AboutMenuTitle {
            get {
                return ResourceManager.GetString("AboutMenuTitle", resourceCulture);
            }
        }
        
        internal static string AboutPageContent {
            get {
                return ResourceManager.GetString("AboutPageContent", resourceCulture);
            }
        }
        
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        internal static string FAQMenuTitle {
            get {
                return ResourceManager.GetString("FAQMenuTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackMenuTitle {
            get {
                return ResourceManager.GetString("FeedbackMenuTitle", resourceCulture);
            }
        }
        
        internal static string GuideMenuTitle {
            get {
                return ResourceManager.GetString("GuideMenuTitle", resourceCulture);
            }
        }
        
        internal static string HomeMenuTitle {
            get {
                return ResourceManager.GetString("HomeMenuTitle", resourceCulture);
            }
        }
        
        internal static string ScanMenuTitle {
            get {
                return ResourceManager.GetString("ScanMenuTitle", resourceCulture);
            }
        }
        
        internal static string TermsMenuTitle {
            get {
                return ResourceManager.GetString("TermsMenuTitle", resourceCulture);
            }
        }
        
        internal static string TutorialMenuTitle {
            get {
                return ResourceManager.GetString("TutorialMenuTitle", resourceCulture);
            }
        }
        
        internal static string VaccineInvalidSHCCodeText {
            get {
                return ResourceManager.GetString("VaccineInvalidSHCCodeText", resourceCulture);
            }
        }
        
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
    }
}
