//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProofOfVaccine.Mobile.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProofOfVaccine.Mobile.AppResources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuTitle {
            get {
                return ResourceManager.GetString("AboutMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque vitae gravida metus. Vestibulum elit quam, placerat ut sollicitudin luctus, consectetur in nibh. Donec sem turpis, pulvinar ac ligula quis, fringilla rhoncus enim. Vestibulum elit quam, placerat ut sollicitudin luctus, consectetur in nibh..
        /// </summary>
        internal static string AboutPageContent {
            get {
                return ResourceManager.GetString("AboutPageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this App.
        /// </summary>
        internal static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Vaccine.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of Vaccination.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FAQMenuTitle {
            get {
                return ResourceManager.GetString("FAQMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        internal static string FeedbackMenuTitle {
            get {
                return ResourceManager.GetString("FeedbackMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not meet public health guidelines.
        /// </summary>
        internal static string FhirFormatInvalidText {
            get {
                return ResourceManager.GetString("FhirFormatInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidelines.
        /// </summary>
        internal static string GuideMenuTitle {
            get {
                return ResourceManager.GetString("GuideMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeMenuTitle {
            get {
                return ResourceManager.GetString("HomeMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid QR code.
        /// </summary>
        internal static string InvalidScanText {
            get {
                return ResourceManager.GetString("InvalidScanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scan.
        /// </summary>
        internal static string NewScanButtonText {
            get {
                return ResourceManager.GetString("NewScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Code.
        /// </summary>
        internal static string ScanButtonText {
            get {
                return ResourceManager.GetString("ScanButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Confirm.
        /// </summary>
        internal static string ScanErrorMessage {
            get {
                return ResourceManager.GetString("ScanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!.
        /// </summary>
        internal static string ScanErrorTitleText {
            get {
                return ResourceManager.GetString("ScanErrorTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Scan.
        /// </summary>
        internal static string ScanMenuTitle {
            get {
                return ResourceManager.GetString("ScanMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string ScanSuccessDetailText {
            get {
                return ResourceManager.GetString("ScanSuccessDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed!.
        /// </summary>
        internal static string ScanSuccessTitleText {
            get {
                return ResourceManager.GetString("ScanSuccessTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms &amp; Conditions.
        /// </summary>
        internal static string TermsMenuTitle {
            get {
                return ResourceManager.GetString("TermsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        internal static string TutorialMenuTitle {
            get {
                return ResourceManager.GetString("TutorialMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not meet public health guidelines.
        /// </summary>
        internal static string VaccineCodeInvalidText {
            get {
                return ResourceManager.GetString("VaccineCodeInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not meet public health guidelines.
        /// </summary>
        internal static string VaccineDateInvalidText {
            get {
                return ResourceManager.GetString("VaccineDateInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not meet public health guidelines.
        /// </summary>
        internal static string VaccineDosageInvalidText {
            get {
                return ResourceManager.GetString("VaccineDosageInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate code issuer.
        /// </summary>
        internal static string VaccineInvalidSHCCodeText {
            get {
                return ResourceManager.GetString("VaccineInvalidSHCCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Guidlines.
        /// </summary>
        internal static string ViewGuideButtonText {
            get {
                return ResourceManager.GetString("ViewGuideButtonText", resourceCulture);
            }
        }
    }
}
